name: Generate Snake

on:
workflow_dispatch:
schedule:
- cron: "0 0 * * *"

jobs:
snake:
runs-on: ubuntu-latest

```
steps:
  - uses: Platane/snk@v3
    with:
      github_user_name: tejaspokale22
      outputs: dist/github-contribution-grid-snake.svg

  - name: Upload artifact
    uses: actions/upload-artifact@v4
    with:
      name: snake
      path: dist/github-contribution-grid-snake.svg
```
